### ISSUE TITLE
[2.1] build issues

### ISSUE THREAD

**Issue by wookietreiber** [ViennaRNA/RNAz#8]
I recently tried to build rnaz/2.1 on an up-to-date Arch Linux using gcc 5.1.0 and I get a lot of warnings like this one for both `HairpinE` and `LoopEnergy`:

```
fold.c:873:13: warning: ‘P’ is static but used in inline function ‘LoopEnergy’ which is not static
    energy = P->int21[type][type_2][si1][sq1][sj1];                                               
```

Also, linking fails, though this is maybe related to the abovementioned warnings:

```
g++ -o RNAz RNAz.o rnaz_utils.o svm_helper.o zscore.o cmdline.o strand.o svm.o -L../librna -lRNA -lm 
../librna/libRNA.a(alifold.o): In function `alifold':
/tmp/makepkg/rnaz/src/RNAz-2.1/librna/alifold.c:186: undefined reference to `HairpinE'
/tmp/makepkg/rnaz/src/RNAz-2.1/librna/alifold.c:203: undefined reference to `LoopEnergy'
/tmp/makepkg/rnaz/src/RNAz-2.1/librna/alifold.c:465: undefined reference to `HairpinE'
/tmp/makepkg/rnaz/src/RNAz-2.1/librna/alifold.c:479: undefined reference to `LoopEnergy'
collect2: error: ld returned 1 exit status
Makefile:242: recipe for target 'RNAz' failed
make[2]: *** [RNAz] Error 1
```

**Comment by wookietreiber** [comment]
Note, at a machine that runs on CentOS 6 with gcc 4.9.2 the compilation shows neither these warnings nor fails at linking.

**Comment by skiwithuge** [comment]
hi,
did you resolve the problem?
I've tried into two different machines with 
gcc v 5.3 (linux mint 17.3)
and another one with gcc v4.4 (CentOS release 6.8)
but I have the same error

**Comment by wookietreiber** [comment]
Well, there is a very simple solution, and that is to compile with an explicit, older C standard, like `-std=gnu89`. You can apply this solution by setting `CFLAGS` when running `configure`, e.g.:

``` bash
./configure CFLAGS="-std=gnu89 -g -O2" --prefix=/usr
```

**Note:** I also added the `-g -O2` flags because those are the standard ones that would otherwise be overwritten when supplying `CFLAGS` like that

---

 However, this just avoids the issue by not talking about it - there is a reason why this was addressed by later C standards. I would not accept this as a solution to this issue. I would rather patch rnaz to comply to newer C standards.

**Comment by riasc** [comment]
When I try this solution. I'm getting the following error:

```
configure: loading site script /usr/share/site/x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/tools/src/RNAz-2.1':
configure: error: C compiler cannot create executables
See `config.log' for more details
```

with

```
/* confdefs.h */
#define PACKAGE_NAME "RNAz"
#define PACKAGE_TARNAME "RNAz"
#define PACKAGE_VERSION "2.1"
#define PACKAGE_STRING "RNAz 2.1"
#define PACKAGE_BUGREPORT "wash@mit.edu"
#define PACKAGE_URL ""
#define PACKAGE "RNAz"
#define VERSION "2.1"

configure: exit 77
```

**Comment by rookie321** [comment]
I am still getting the same error even after configuring using 
`./configure CFLAGS="-std=gnu89 -g -O2" --prefix=/usr`
Anything that I am missing?

**Comment by RaumZeit** [comment]
These issues should have been resolved with version 2.1.1
